"""Board #568: the PostgreSQL backend keeps SQLite's one-writer-at-a-time property across hosts.

The service's invariants (one winner per claim, monotonic fencing tokens, an unforked audit
chain) are written against SQLite's `BEGIN IMMEDIATE`. These tests pin what the PostgreSQL
backend substitutes for it, and each mechanism is paired with a control that shows the
measurement can fail:

- the read-modify-write counter loses updates with NO lock under READ COMMITTED, so its
  "no lost update" assertion is not vacuous;
- taking the lock INSIDE the serializable snapshot is still correct but aborts under
  contention, so "zero aborts" measures the lock order rather than luck.

Tests that need a server use the ``postgres_url`` fixture (ACP_TEST_POSTGRES_URL) and skip
without one; the translation tests always run.
"""

from __future__ import annotations

import sqlite3
import threading
import time
from concurrent.futures import ThreadPoolExecutor

import pytest
from fastapi.testclient import TestClient

from agent_control_plane.app import create_app
from agent_control_plane.config import Settings
from agent_control_plane.database import Database, StorageBusyError
from agent_control_plane.postgres_backend import (
    PostgresConnection,
    UnsupportedSqlError,
    advisory_lock_key,
    redact_url,
    split_script,
    translate_ddl,
    translate_query,
)
from agent_control_plane.schema_version import SchemaVersionError
from agent_control_plane.side_effects import RECEIPT_SCHEMA

psycopg = pytest.importorskip("psycopg")


# ------------------------------------------------------------------ translation (no server) --


def test_placeholders_translate_outside_literals_only():
    assert (
        translate_query("SELECT * FROM t WHERE a = ? AND b = '?' AND c LIKE 'x%' -- ?\n")
        == "SELECT * FROM t WHERE a = %s AND b = '?' AND c LIKE 'x%%' -- ?\n"
    )
    assert translate_query('SELECT "we?ird" FROM t WHERE a = ?') == (
        'SELECT "we?ird" FROM t WHERE a = %s'
    )


def test_ddl_maps_column_types_but_not_literals():
    ddl = translate_ddl(
        "CREATE TABLE x (sequence INTEGER PRIMARY KEY AUTOINCREMENT, "
        "n INTEGER NOT NULL DEFAULT 0, t TEXT NOT NULL DEFAULT 'INTEGER TEXT')"
    )
    assert "sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    assert "n BIGINT NOT NULL" in ddl
    assert 't TEXT COLLATE "C" NOT NULL' in ddl
    assert "DEFAULT 'INTEGER TEXT'" in ddl


def test_script_split_respects_quoted_semicolons_and_comments():
    statements = split_script(
        "-- leading; comment\nCREATE TABLE a (x TEXT DEFAULT ';');\n\nCREATE INDEX i ON a(x);\n"
    )
    assert statements == ["CREATE TABLE a (x TEXT DEFAULT ';')", "CREATE INDEX i ON a(x)"]


def test_lock_key_is_stable_scoped_and_64_bit():
    first = advisory_lock_key("acp.public")
    assert first == advisory_lock_key("acp.public")
    assert first != advisory_lock_key("acp.tenant_b")
    assert -(2**63) <= first < 2**63


def test_urls_are_redacted_before_they_can_be_logged():
    assert redact_url("postgresql://acp:s3cret@db:5432/acp") == "postgresql://acp:***@db:5432/acp"
    assert redact_url("postgresql://acp@db/acp") == "postgresql://acp@db/acp"


# ------------------------------------------------------------------------- live server -----


def _columns_sqlite(path: str) -> dict[str, list[str]]:
    connection = sqlite3.connect(path)
    try:
        tables = [
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
            )
        ]
        return {
            table: [row[1] for row in connection.execute(f"PRAGMA table_info({table})")]
            for table in sorted(tables)
        }
    finally:
        connection.close()


def _columns_postgres(url: str) -> dict[str, list[str]]:
    with psycopg.connect(url) as connection:
        rows = connection.execute(
            """
            SELECT table_name, column_name FROM information_schema.columns
            WHERE table_schema = current_schema()
            ORDER BY table_name, ordinal_position
            """
        ).fetchall()
    columns: dict[str, list[str]] = {}
    for table, column in rows:
        columns.setdefault(table, []).append(column)
    return columns


@pytest.mark.postgres_backend
def test_schema_on_the_server_has_exactly_the_sqlite_tables_and_columns(postgres_url, tmp_path):
    """Drift gate: SCHEMA is the single source, so a column added for SQLite lands here too."""

    sqlite_path = str(tmp_path / "parity.db")
    for database in (Database(sqlite_path), Database(postgres_url)):
        database.initialize()
        with database.connect() as connection:
            connection.executescript(RECEIPT_SCHEMA)

    postgres = _columns_postgres(postgres_url)
    assert Database(postgres_url).dialect == "postgresql"
    assert "audit_events" in postgres and "resource_leases" in postgres
    assert postgres == _columns_sqlite(sqlite_path)


@pytest.mark.postgres_backend
def test_initialize_is_idempotent_and_refuses_a_newer_schema(postgres_url):
    database = Database(postgres_url)
    database.initialize()
    database.initialize()
    with database.connect() as connection:
        connection.execute("UPDATE meta SET value = '999' WHERE key = 'schema_version'")
    with pytest.raises(SchemaVersionError, match="schema version 999"):
        Database(postgres_url).initialize()


@pytest.mark.postgres_backend
def test_sqlite_only_sql_fails_loudly_instead_of_doing_something_nearby(postgres_url):
    database = Database(postgres_url)
    database.initialize()
    with pytest.raises(UnsupportedSqlError, match="PRAGMA"):
        with database.connect() as connection:
            connection.execute("PRAGMA journal_mode")


@pytest.mark.postgres_backend
def test_rows_behave_like_sqlite_rows(postgres_url):
    database = Database(postgres_url)
    database.initialize()
    event = database.append_audit("probe.row", "test", {"k": "v"})
    row = database.one(
        "SELECT sequence, event_type FROM audit_events WHERE event_id = ?", (event["event_id"],)
    )
    assert row[0] == row["sequence"] == event["sequence"]
    assert dict(row) == {"sequence": event["sequence"], "event_type": "probe.row"}
    assert database.verify_audit_chain() == (True, 1, None)


def _counter(database: Database) -> None:
    with database.connect() as connection:
        connection.execute(
            "CREATE TABLE IF NOT EXISTS counter (id INTEGER PRIMARY KEY, value INTEGER)"
        )
        connection.execute(
            "INSERT INTO counter (id, value) VALUES (1, 0) ON CONFLICT (id) DO NOTHING"
        )


def _increment(database: Database) -> str:
    try:
        with database.connect() as connection:
            connection.execute("BEGIN IMMEDIATE")
            value = connection.execute("SELECT value FROM counter WHERE id = 1").fetchone()[0]
            time.sleep(0.002)  # widen the read-modify-write window
            connection.execute("UPDATE counter SET value = ? WHERE id = 1", (value + 1,))
    except StorageBusyError as error:
        return error.code
    return "ok"


class _LockInsideSnapshot(PostgresConnection):
    """The tempting wrong order: serializable transaction first, xact lock as its first statement."""

    def begin_write(self) -> None:
        if self._write:
            return
        self._raw.autocommit = False
        self._raw.isolation_level = psycopg.IsolationLevel.SERIALIZABLE
        self._raw.execute("SELECT pg_advisory_xact_lock(%s)", (self._lock_key,))
        self._write = True


class _NoLockReadCommitted(PostgresConnection):
    """Known-broken control: what the backend would be without its lock or its isolation level."""

    def begin_write(self) -> None:
        if self._write:
            return
        self._raw.autocommit = False
        self._raw.isolation_level = psycopg.IsolationLevel.READ_COMMITTED
        self._write = True


def _race_counter(
    url: str, connection_class: type[PostgresConnection] | None
) -> tuple[int, dict[str, int]]:
    setup = Database(url)
    setup.initialize()
    _counter(setup)
    threads, per_thread = 8, 15
    databases = []
    for _ in range(threads):
        database = Database(url)
        if connection_class is not None:
            database._backend.connection_class = connection_class
        databases.append(database)
    start = threading.Barrier(threads)

    def run(database: Database) -> list[str]:
        start.wait(timeout=30)
        return [_increment(database) for _ in range(per_thread)]

    with ThreadPoolExecutor(max_workers=threads) as pool:
        outcomes = [code for batch in pool.map(run, databases) for code in batch]
    tally: dict[str, int] = {}
    for code in outcomes:
        tally[code] = tally.get(code, 0) + 1
    final = setup.one("SELECT value FROM counter WHERE id = 1")[0]
    return final, tally


@pytest.mark.postgres_backend
def test_lock_before_snapshot_serialises_writers_with_no_aborts_and_no_lost_updates(postgres_url):
    final, tally = _race_counter(postgres_url, None)
    assert tally == {"ok": 120}, tally
    assert final == 120


@pytest.mark.postgres_backend
def test_control_lock_inside_snapshot_is_correct_but_aborts_under_contention(postgres_url):
    final, tally = _race_counter(postgres_url, _LockInsideSnapshot)
    assert tally.get("storage_serialization_conflict", 0) > 0, tally
    assert final == tally["ok"], "SERIALIZABLE must still refuse every lost update"


@pytest.mark.postgres_backend
def test_control_without_lock_or_serializable_loses_updates(postgres_url):
    final, tally = _race_counter(postgres_url, _NoLockReadCommitted)
    assert tally == {"ok": 120}, tally
    assert final < 120, "the counter cannot detect a lost update, so the green tests prove nothing"


@pytest.mark.postgres_backend
def test_lock_wait_past_its_timeout_is_a_503_that_names_no_host(postgres_url):
    app = create_app(
        Settings(
            database_path=postgres_url,
            admin_key="test-admin",
            signing_key="test-signing-key-with-enough-entropy",
            issuer="test-control-plane",
        )
    )
    backend = app.state.database._backend
    backend.lock_timeout_seconds = 0.3
    holder = psycopg.connect(postgres_url, autocommit=True)
    try:
        holder.execute("SELECT pg_advisory_lock(%s)", (backend._lock_key,))
        with TestClient(app) as client:
            response = client.post(
                "/v1/agents",
                headers={"X-Control-Plane-Key": "test-admin"},
                json={"name": "blocked", "owner": "ops@example.com", "role": "worker"},
            )
    finally:
        holder.close()
    assert response.status_code == 503, response.text
    assert response.headers["retry-after"] == "1"
    assert response.json() == {
        "error": "storage_lock_timeout",
        "message": "storage is busy; retry the request",
    }
    assert "127.0.0.1" not in response.text


@pytest.mark.postgres_backend
def test_a_holder_that_goes_silent_mid_transaction_is_evicted_and_cannot_commit(postgres_url):
    """A client host that partitions while holding the write lock must not wedge every host.

    The server's idle timeout ends the silent session, which rolls its transaction back and
    releases the session lock. The survivor then gets through, and the evicted holder's
    eventual commit fails instead of landing late.
    """

    Database(postgres_url).initialize()
    silent = Database(postgres_url)
    silent._backend.idle_timeout_seconds = 1.0
    survivor = Database(postgres_url)
    survivor._backend.lock_timeout_seconds = 10.0

    context = silent.connect()
    connection = context.__enter__()
    connection.execute("BEGIN IMMEDIATE")
    connection.execute(
        "UPDATE meta SET value = 'from-the-partitioned-host' WHERE key = 'written_by'"
    )

    started = time.monotonic()
    survivor.execute("UPDATE meta SET value = 'survivor' WHERE key = 'written_by'")
    waited = time.monotonic() - started

    with pytest.raises(StorageBusyError):
        context.__exit__(None, None, None)
    assert 0.5 < waited < 8, f"survivor waited {waited:.2f}s"
    assert survivor.one("SELECT value FROM meta WHERE key = 'written_by'")[0] == "survivor"
